const ROLES = {
  SUPERADMIN: 'superadmin',
  SCHOOL_ADMINISTRATOR: 'school_administrator',
};

const PERMISSIONS = {
  SCHOOLS: {
    CREATE: 'schools:create',
    READ: 'schools:read',
    UPDATE: 'schools:update',
    DELETE: 'schools:delete',
    LIST: 'schools:list',
  },
  CLASSROOMS: {
    CREATE: 'classrooms:create',
    READ: 'classrooms:read',
    UPDATE: 'classrooms:update',
    DELETE: 'classrooms:delete',
    LIST: 'classrooms:list',
  },
  STUDENTS: {
    CREATE: 'students:create',
    READ: 'students:read',
    UPDATE: 'students:update',
    DELETE: 'students:delete',
    LIST: 'students:list',
    TRANSFER: 'students:transfer',
  },
};

const ROLE_PERMISSIONS = {
  [ROLES.SUPERADMIN]: [
    PERMISSIONS.SCHOOLS.CREATE,
    PERMISSIONS.SCHOOLS.READ,
    PERMISSIONS.SCHOOLS.UPDATE,
    PERMISSIONS.SCHOOLS.DELETE,
    PERMISSIONS.SCHOOLS.LIST,
    PERMISSIONS.CLASSROOMS.CREATE,
    PERMISSIONS.CLASSROOMS.READ,
    PERMISSIONS.CLASSROOMS.UPDATE,
    PERMISSIONS.CLASSROOMS.DELETE,
    PERMISSIONS.CLASSROOMS.LIST,
    PERMISSIONS.STUDENTS.CREATE,
    PERMISSIONS.STUDENTS.READ,
    PERMISSIONS.STUDENTS.UPDATE,
    PERMISSIONS.STUDENTS.DELETE,
    PERMISSIONS.STUDENTS.LIST,
    PERMISSIONS.STUDENTS.TRANSFER,
  ],
  [ROLES.SCHOOL_ADMINISTRATOR]: [
    PERMISSIONS.CLASSROOMS.CREATE,
    PERMISSIONS.CLASSROOMS.READ,
    PERMISSIONS.CLASSROOMS.UPDATE,
    PERMISSIONS.CLASSROOMS.DELETE,
    PERMISSIONS.CLASSROOMS.LIST,
    PERMISSIONS.STUDENTS.CREATE,
    PERMISSIONS.STUDENTS.READ,
    PERMISSIONS.STUDENTS.UPDATE,
    PERMISSIONS.STUDENTS.DELETE,
    PERMISSIONS.STUDENTS.LIST,
    PERMISSIONS.STUDENTS.TRANSFER,
  ],
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

const CACHE_TTL = {
  SHORT: 300, // 5 minutes
  MEDIUM: 1800, // 30 minutes
  LONG: 3600, // 1 hour
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  HTTP_STATUS,
  CACHE_TTL,
};
